- name: Programming Bootcamp 2021.10
  id: bootcamp-2021-10
  students:
    - name: Foo
      email: gabor@code-maven.com
    - name: Bar
      email: gabor@perlmaven.com
  exercises:
    - title: Hello world
      url: https://code-maven.com/slides/perl/exercise-hello-world
    - title: Rectangular
      url: https://code-maven.com/slides/perl/exercise-rectangular
- name: Advanced 2021.06
  id: advanced-2021-06
  students:
    - name: Foo
      email: gabor@code-maven.com
    - name: Advanced Bar
      email: other@perlmaven.com
  exercises:
    - title: test blogs.perl.org
      url: https://code-maven.com/slides/perl/exercise-blogs-perl-org
- name: Another course
  id: another-date
  students:
    - name: Advanced Bar
      email: other@perlmaven.com
  exercises:
    - title: test blogs.perl.org
      url: https://code-maven.com/slides/perl/exercise-blogs-perl-org
