name: Programming Bootcamp 2021.10
students:
  - name: Foo
    email: gabor@code-maven.com
  - name: Bar
    email: gabor@perlmaven.com
exercises:
  - title: Hello world
    url: https://slides.code-maven.com/perl/exercise-hello-world
  - title: Rectangular
    url: https://slides.code-maven.com/perl/exercise-rectangular
